name: Tests

on:
  pull_request:
  push:

jobs:
  composer-validate:
    name: Composer validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

  cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fix CS
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - description: 'Lowest dependencies'
            php: '8.1'
            composer_option: '--prefer-lowest'

          - description: 'PHP-version test'
            php: '8.1'
          - description: 'PHP-version test'
            php: '8.2'
          - description: 'PHP-version test'
            php: '8.3'
          - description: 'PHP-version test'
            php: '8.4'

          - description: 'Symfony 6.1'
            php: '8.1'
            symfony: 6.1.*
          - description: 'Symfony 7'
            php: '8.2'
            symfony: ^7.3
            dev: true

          - description: 'Dev dependencies'
            php: '8.3'
            dev: true

    name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ matrix.php }}-${{ matrix.symfony }}-${{ matrix.composer_option }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Change Symfony-Dependencies
        if: matrix.symfony
        run: |
          sed -ri 's/"symfony\/(framework-bundle)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony }}'"/' composer.json;
      - name: Set composer minimum-stability to "dev"
        if: matrix.dev
        run: composer config minimum-stability dev
      - run: composer update --no-interaction --no-progress --ansi ${{ matrix.composer_option }}
      - run: vendor/bin/phpunit --display-warnings

  coverage:
    name: PHPUnit with Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run PHPUnit with Code Coverage
        run: vendor/bin/phpunit --display-warnings --coverage-clover coverage.xml
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
